glowventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import delete, edit_item, get_product_json, add_product_ajax, create_item_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item/', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>/', delete, name='delete'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()
    category = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "price", "description", "category"]

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import datetime, json

@login_required(login_url='/login')
# Create your views here.
def show_main(request):
    item = Item.objects.filter(user=request.user)
    data_count = item.count()
    context = {
        'application_name': 'Glowventory',
        'name': request.user.username,
        'class': 'PBP C',
        'items': item,
        'data_count': data_count,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def delete(request, id):
    item = Item.objects.get(id=id)
    item.delete()
    return redirect('main:show_main')

def edit_item(request, id):
    # Get product berdasarkan ID
    product = Item.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ItemForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        description = request.POST.get("description")
        category = request.POST.get("category")
        user = request.user

        new_product = Item(name=name, amount=amount, price=price, description=description, category=category, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data['amount']),
            price = int(data["price"]),
            description = data["description"],
            category = data['category'],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %} 

{% block content %}

<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap');
    body {
        font-family: 'Poppins', sans-serif;
        background-color: #f0f8ff; /* Baby Blue / Soft Blue */
        text-align: center;
        margin: 0;
        padding: 20px; /* Added padding */
    }
    h1, h5, p {
        font-family: 'Poppins', sans-serif; /* Change font to Poppins */
        color: #000080; /* Dark Blue */
        margin: 10px 0; /* Adjusted margin */
    }
    table {
        width: 70%; /* Adjusted width */
        margin: 20px auto; /* Adjusted margin */
        border-collapse: separate;
        border-spacing: 0;
        overflow: hidden; /* Hide overflowing borders */
    }
    th, td {
        border: 2px solid #ccc; /* Light gray border */
        padding: 10px;
        text-align: center;
    }
    th {
        background-color: #f5f5f5; /* Light gray */
        color: #000080; /* Dark Blue */
    }
    td {
        background-color: #fff; /* Broken white background */
    }
    input[type="text"] {
        width: 100%; /* Set the width to 100% for the text input fields */
        box-sizing: border-box; /* Include padding and border in the width */
        font-family: 'Verdana', sans-serif; /* Change the font to Verdana */
        font-size: 14px; /* Adjust the font size */
    }
    input[name="amount"], input[name="price"] {
        width: 100%; /* Adjusted width for amount and price */
        font-family: 'Verdana', sans-serif; /* Change the font to Verdana */
        font-size: 14px; /* Adjust the font size */
    }
    input[name="category"], input[name="description"] {
        font-family: 'Verdana', sans-serif;
        font-size: 14px;
    }
    a {
        text-decoration: none;
        color: #000080; /* Dark Blue */
    }
    button {
        background-color: #000080; /* Dark Blue */
        color: white;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        border-radius: 5px; /* Rounded corners */
        font-size: 14px; /* Font size adjustment */
        margin-top: 10px; /* Margin adjustment */
    }
    button:hover {
        background-color: #004d40; /* Darker Soft Blue on hover */
    }
</style>

<h1>Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Edit Item</button>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap');
    body {
        font-family: 'Montserrat', sans-serif;
        background-color: #f9f9f9; /* Light Gray */
        text-align: center;
        margin: 0;
        padding: 20px; /* Add some padding to create space around the content */
    }
    h1 {
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color: #00838f; /* Soft Blue */
    }
    p {
        color: #333; /* Dark Gray */
        margin: 5px 0;
    }
    table {
        width: 90%; /* Increase the width of the table */
        margin: 10px auto;
        border-collapse: separate;
        border-spacing: 0 15px;
    }
    table, th, td {
        border: 2px solid #ccc; /* Light Gray */
        padding: 10px;
    }
    th {
        background-color: #f0f0f0; /* Light Gray */
        color: #333; /* Dark Gray */
    }
    td {
        background-color: #fff; /* White */
    }
    a {
        text-decoration: none;
        color: #00838f; /* Soft Blue */
    }
    button {
        background-color: #e0e0e0; /* Lighter Gray */
        color: #333; /* Dark Gray */
        border: 2px solid #ccc; /* Gray border */
        border-color: darkgrey;
        padding: 10px 20px;
        cursor: pointer;
        border-radius: 5px; /* Optional: Add border-radius for a softer look */
    }
    button:hover {
        background-color: #f0f0f0; /* Light Gray on hover */
    }
    .login {
        padding: 20px;
        border-radius: 10px;
        background-color: #fff; /* White */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Shadow effect */
        margin: 50px auto; /* Centered */
        max-width: 500px; /* Increase the max width of the container */
        background-color: #f9f9f9; /* Light Gray for the container */
    }
</style>

<div class="login">
    <h1>Glowventory</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <button class="btn login_btn" type="submit">Login</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-hQ2yXBUkth9eYUMA+wF33GSLxMyfcrCyP6oJ4MRmF87DfuYng/wjszpn7rfXtDpAyKO8rTRFlBKuxZGiK7oJ6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f0f8ff; /* Baby Blue / Soft Blue */
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        nav.navbar {
            width: 100%;
            font-size: 18px;
            color: white;
            background-color: #000080; /* Dark Blue */
            display: flex;
            justify-content: space-between;
            padding: 10px 10px;
            text-align: center;
        }

        nav.navbar a {
            text-align: left;
            color: white;
            margin-left: 20px;
            font-weight: bold;
        }

        .user-info.welcome-text {
            font-family: Verdana, sans-serif; /* Change font to Verdana */
            font-size: 12px; /* Adjusted font size */
            margin-top: 3px; /* Adjusted margin */
            align-items: baseline;
        }

        .logout-button {
            display: flex;
            align-items: center;
            margin-right: 20px; /* Adjusted margin */
        }
        
        .logout-button i {
            margin-right: 5px; /* Adjusted margin */
        }

        .container {
            padding: 8px;
            text-align: center;
        }

        h1 {
            color: #000080; /* Dark Blue */
            padding: 20px 0;
        }

        h4{
            color: #333; /* Dark Gray */
            font-size: 13px;
        }

        table {
            width: 90%;
            max-width: 100%;
            margin: 0 auto;
            margin-top: 20px;
            text-align: center;
            border: 2px solid #ccc; /* Border color: Light Gray */
            background-color: white; /* Background color: White */
        }

        th, td {
            border: 1px solid #ccc; /* Border color: Light Gray */
            padding: 15px; /* Adjusted padding for cells */
            text-align: center;
            background-color: #f9f9f9; /* Background color: Very Light Gray */
            color: #333; /* Text color: Dark Gray */
        }

        th {
            background-color: #ccc; /* Header background color: Light Gray */
            color: #333; /* Header text color: Dark Gray */
        }

        td {
            font-size: 14px; /* Adjusted font size for cells */
        }

        a.button {
            text-decoration: none;
            color: white;
            background-color: #00838f; /* Soft Blue */
            padding: 12px 24px;
            border-radius: 5px;
            font-size: 14px;
            transition: background-color 0.3s;
            margin: 10px 10px 0; /* Adjusted margin */
            display: inline-block;
        }

        a.button:hover {
            background-color: #004d40; /* Darker Soft Blue on hover */
        }

        p {
            margin: 10px 0 5px; /* Adjusted margin */
            font-size: 12px; /* Reduced font size for item count */
            padding-bottom: 2%;
            padding-top: 5%;
        }

        .last-login {
            font-size: 10px; /* Reduced font size for last login */
            color: #000080; /* Dark Blue */
            margin-top: 10px; /* Adjusted margin top */
            padding-top: 8%;
        }

        .container {
            padding: 20px;
            text-align: center;
            margin-bottom: 50px; /* Tambahkan margin bottom yang cukup besar */
            margin-top: 50px;
        }

        .footer {
            bottom: 0;
            width: 100%;
            background-color: #f0f0f0;
            padding: 10px;
            padding-left: 5%;
            text-align: left;
            text-decoration: solid;
            z-index: 999; /* Atur z-index untuk memastikan footer muncul di atas konten lain */
            font-family: 'Lato';
        }

        .bg-1 {
            background-color: #7487cf; /* Green */
            color: #ffffff;
        }
        .bg-2 {
            background-color: #9db2df; /* Dark Blue */
            color: #14131f;
            padding: 10px;
            margin-bottom: 3px;
            font-family: 'Lato';
            font-weight: 200;
            font-style: inherit;
            font: 300;
        }
        .bg-3 {
            background-color: #ffffff; /* White */
            color: #555555;
        }

        .container-fluid.bg-2 {
            padding: 40px; /* Adjusted padding */
        }

        .container-fluid.bg-2 h3 {
            font-size: 24px; /* Adjusted font size */
            font-family: 'Poppins', sans-serif;
            color: #14131f;
        }

        .container-fluid.bg-2 p {
            font-size: 18px; /* Adjusted font size */
            color: #333; /* Adjusted text color */
            margin-bottom: 20px; /* Adjusted margin */
        }

        /* Untuk tombol "Delete" */
        .btn-danger {
            background-color: #9db2df; /* Warna yang setara dengan warna pada tabel */
            color: #14131f; /* Warna teks agar kontras dengan latar belakang */
        }

        .btn-danger:hover {
            background-color: #7487cf; /* Warna saat dihover */
        }

        /* Untuk tombol "Add Item" dan "Edit Item" */
        .btn-primary {
            background-color: #9db2df; /* Warna yang setara dengan warna pada tabel */
            color: #14131f; /* Warna teks agar kontras dengan latar belakang */
        }

        .btn-primary:hover {
            background-color: #7487cf; /* Warna saat dihover */
        }

        h4{
            padding: 5px;
        }
        .card-item {
            width: 250px; /* Atur lebar kartu */
            height: 300px; /* Atur tinggi kartu */
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px; /* Tambahkan margin agar terlihat jarak antar kartu */
            margin-top: 50px;
        }

        .card-item h2 {
            font-size: 18px;
            margin-bottom: 10px;
            color: #000080;
        }

    </style>
    
</head>


<body>
    <nav class="navbar">
        <a href="#"><b>GLOWVENTORY PAGE</b></a>
        <div class="user-info welcome-text">
            Welcome &nbsp{{ name }}
        </div>
        <a class="logout-button" href="{% url 'main:logout' %}">
            <i class="fas fa-sign-out-alt"></i> Logout
        </a>
    </nav>
    
    <div class="container">
        <h1>Welcome to Glowventory Page</h1>
    </div>
    
    <div class="container-fluid bg-2 text-center">
        <h3>About Us</h3>
        <p>Glowventory  is a powerful and user-friendly platform designed to assist skincare enthusiasts in organizing and managing their skincare products.
            The application is tailored specifically for skincare products, allowing users to keep track of their skincare products and makeup products with its detail.
            The application provides a comprehensive product catalog where users can input details about each skincare or makeup product they own. Users can store information such as 
            product name, amount, price, description of the producet and categories.
        </p>

    </div> 

    <div class="container">
        <h4>Add the best product for you and your glowing skin</h4>
        <div class="card-container" id="product_table"></div>
    
        <p>You have {{ data_count }} items in this application</p>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>
    </div>

    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="text" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="col-form-label">Category:</label>
                            <input type="text" class="form-control" id="category" name="category"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>
    
    <div class="footer">
        Glowventory by Bella | Last login: {{ last_login }}
    </div>

    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }
    
        async function refreshProducts() {
            const productTable = document.getElementById("product_table");
            productTable.innerHTML = "";

            const products = await getProducts();
            let htmlString = "<div class='row'>";  // Start a new row

            products.forEach((item, index) => {
                if (index % 3 === 0 && index !== 0) {
                    htmlString += "</div><div class='row'>";  // Close previous row and start a new row for every 3 cards
                }

                htmlString += `
                    <div class="col-md-4">
                        <div class="card-item">
                            <div class="card mx-auto p-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h2 class="card-title">${item.fields.name}</h2>
                                    <p class="card-text">Amount: ${item.fields.amount}</p>
                                    <p class="card-text">Price: ${item.fields.price}</p>
                                    <p class="card-text">${item.fields.description}</p>
                                    <p class="card-text">Category: ${item.fields.category}</p>
                                    <a style="justify-content: baseline;" href='edit-item/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                                    <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteProduct(${item.pk})">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>`;
            });

            htmlString += "</div>";  // Close the last row
            productTable.innerHTML = htmlString;
        }

    
        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)
    
            document.getElementById("form").reset()
            return false
        }

        function editProduct(productId) {
            fetch(`{% url 'main:edit_item' 0 %}${productId}/`, {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
        }

        function deleteProduct(productId) {
            fetch(`{% url 'main:delete' 0 %}`.replace("0", productId), {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

        refreshProducts()
        document.getElementById("button_add").onclick = addProduct
    </script>
    
</body>
</html>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap');
    body {
        font-family: 'Montserrat', sans-serif;
        background-color: #e0f7fa; /* Soft Blue */
        text-align: left;
        margin: 0;
        padding: 20px; /* Add some padding to create space around the content */
        font-size: 12px;
    }
    h1, h5, p {
        color: #00838f; /* Soft Blue */
        margin: 5px 0; /* Mengatur margin atas dan bawah */
        text-align: center;
    }
    table {
        width: 100%; /* Lebar tabel 100% */
        border-collapse: separate; /* Menggunakan border-collapse: separate */
        border-spacing: 0 15px; /* Jarak antar border diperbesar */
    }
    table, th, td {
        border: none; /* Menghapus border */
        padding: 10px;
    }
    th {
        background-color: #81c784; /* Soft Green */
        color: white; /* Warna teks header putih */
    }
    td {
        background-color: #f0f0f0; /* Warna latar sel abu-abu muda */
    }
    a {
        text-decoration: none;
        color: #00838f; /* Soft Blue */
    }
    .login {
        padding: 20px;
        border-radius: 10px;
        background-color: #fff; /* White */
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Shadow effect */
        margin: 50px auto; /* Centered */
        max-width: 500px; /* Increase the max width of the container */
        background-color: #f9f9f9; /* Light Gray for the container */
    }
    .login table input {
        width: 100%; /* Text field 100% width */
        box-sizing: border-box; /* Include padding and border in the width */
    }
    .login button {
        background-color: #f0f0f0; /* Light Gray */
        color: #333; /* Dark Gray */
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        width: 100%; /* Button 100% width */
        box-sizing: border-box; /* Include padding and border in the width */
    }
    .login button:hover {
        background-color: #d0d0d0; /* Slightly darker gray on hover */
    }
</style>

<div class="login">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button class="btn login_btn" type="submit">Daftar</button>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock content %}